[package]
name = "small-black-box"
version = "0.1.0"
authors = ["Areg Harutyunyan <sssilver@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "small-black-box"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]

[dependencies]
anyhow = "1.0.72"
bstr = "1.7.0"
esp-idf-svc = { version = "0.51", features = ["embassy-time-driver"] }
esp32-nimble = "0.10"
log = "0.4"
lora-phy = "3.0"
embassy-time = { version = "0.4", features = ["generic-queue-64"] }

[build-dependencies]
embuild = "0.33"
